{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gower
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gower_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gower/gower_{{ version }}.tar.gz
  sha256: f427227d8d155e78871814a8ee9a2bd4d6072c532d36f206f46abd1e2d982674

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
    - llvm-openmp                # [osx]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - llvm-openmp                # [osx]

test:
  commands:
    - $R -e "library('gower')"           # [not win]
    - "\"%R%\" -e \"library('gower')\""  # [win]

about:
  home: https://github.com/markvanderloo/gower
  license: GPL-3
  summary: Compute Gower's distance (or similarity) coefficient between records. Compute the
    top-n matches between records. Core algorithms are executed in parallel on systems
    supporting OpenMP.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gower
# Maintainer: Mark van der Loo <mark.vanderloo@gmail.com>
# License: GPL-3
# Title: Gower's Distance
# LazyData: no
# Type: Package
# LazyLoad: yes
# Authors@R: c( person("Mark", "van der Loo", role=c("aut","cre"),email="mark.vanderloo@gmail.com") , person("David", "Turner", role="ctb"))
# Description: Compute Gower's distance (or similarity) coefficient between records. Compute  the top-n matches between records. Core algorithms are executed in parallel on systems supporting OpenMP.
# Version: 0.2.0
# URL: https://github.com/markvanderloo/gower
# BugReports: https://github.com/markvanderloo/gower/issues
# Date: 2019-03-07
# Suggests: testthat,
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-03-07 13:16:20 UTC; mark
# Author: Mark van der Loo [aut, cre], David Turner [ctb]
# Repository: CRAN
# Date/Publication: 2019-03-07 14:20:03 UTC
