{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gower
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gower_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gower/gower_{{ version }}.tar.gz
  sha256: 296a9d8e5efa8c3a8cc6b92cf38880915753afdef30281629af9dc8eae8315fc

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('gower')"           # [not win]
    - "\"%R%\" -e \"library('gower')\""  # [win]

about:
  home: https://github.com/markvanderloo/gower
  license: GPL-3.0-only
  summary: Compute Gower's distance (or similarity) coefficient between records. Compute  the top-n matches between records. Core algorithms are executed in parallel on systems supporting OpenMP.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gower
# Maintainer: Mark van der Loo <mark.vanderloo@gmail.com>
# License: GPL-3
# Title: Gower's Distance
# LazyData: no
# Type: Package
# LazyLoad: yes
# Authors@R: c( person("Mark", "van der Loo", role=c("aut","cre"),email="mark.vanderloo@gmail.com") , person("David", "Turner", role="ctb"))
# Description: Compute Gower's distance (or similarity) coefficient between records. Compute  the top-n matches between records. Core algorithms are executed in parallel on systems supporting OpenMP.
# Version: 0.2.1
# URL: https://github.com/markvanderloo/gower
# BugReports: https://github.com/markvanderloo/gower/issues
# Suggests: tinytest (>= 0.9.3),
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-05-14 19:35:03 UTC; mark
# Author: Mark van der Loo [aut, cre], David Turner [ctb]
# Repository: CRAN
# Date/Publication: 2019-05-14 21:00:23 UTC
