{% set version = '0.1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gower
  version: {{ version|replace("-", "_") }}

source:
  fn: gower_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gower_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gower/gower_{{ version }}.tar.gz
  sha256: eb91b2d2784d237c7055abcf3cfa4fc0b2226b855a0c29fc5a4e8eaa689079d5

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('gower')"           # [not win]
    - "\"%R%\" -e \"library('gower')\""  # [win]

about:
  home: https://github.com/markvanderloo/gower
  license: GPL-3
  summary: Compute Gower's distance (or similarity) coefficient between records. Compute the
    top-n matches between records. Core algorithms are executed in parallel on systems
    supporting OpenMP.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
