# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WlGcYVKA0JEgmZ1GvyQrqpXBE9bwbXjyikdGdSrbXx99ZrmxMEAbGL4prtzytAxJcwcXA7gxHYawF3sEDY3GMenhtqU/wdONTYfABHI2b+msT4PGQ6NFP5Muqo7FiDBOWOhjHtHK/AXdAt+91WnzuLQGTdXjaxXkRo85B4sSpSBn5YooV+PNC++qeUDtmYjPOVR4WDDvo07nzZF4/e4H/SQPFKp+axuPkTQ80ow0tya+buvzyIK6F6H0pqZXH9yD3GlNmrdQx2Sc8p3m5gF/FB5cHLP1HK/iMOgg9qJZtCi6GZTFzM9lmayGedFHYh7rSqMvaK7E8dcoEFOtCpSUJKNsM6R5Q76+SaczaFKFHs1N62JisFZU4gIuDLIablocRloeKj7mOe0YmNXwoMYLQnmz2uNzW+L5XNYjgcKjA/Vp4deUrrEAeYSTwz49Hdu4hBVAvcTEcrPGi+Jo50GrjPAVg8nMzmXciLKUApAzj4ZVXoXJcf+hQ0gt/25BxvKiQ1+pl7CO+TQsyLrI2CLuPA46eWARUYkJZZgFnejSA6/2dnrRjvRXTUVvi5bUlaVgAN82y7a+4y48xJ2X14O+dQPMLRBhhZ07hf9T/p6Pv4mrCqleiOGTOHke4wpc1yNkq3Ahqw+99jPxSW3P3mMCfBRfX5bgpNNkaOutFcrIjMA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
