travis:
  secure:
    BINSTAR_TOKEN: MYLsL40bPPjuGtjZhW1U2fuJEGWI5+AGZjvBrC/ZBmpzYSV9aa3BAsPOsuvl8+VTyfyCwyaLzEz9ydX3pu0Jox5tfwz9daYZQXyosZYyftbbmQTZqXug9FLKjKF0TvYjdHpedWM6K+Cblw4TtSRfU/W9to/4U5tKOJ10OvTfTFcKTmwwpXqjzAGfuVXpFsRGTbhMgRLXXGBBBmiZnm4sS04h3Qm8SpKrlCFh4lXJ0kzL4pkaAw5/F6SSXDghDBh/T7dSOSjqGLzauczo3M6amSy/vW2lh6uJSNzXQ9JHHwMnxzUZQ/ajqgAuwxcN1ngvI2QfVYfuARXeLCAp/UquE+Z2CtZRHJrYtt33s2E5VBII+e1Wn/hqqSXPszorYEycRsIdl+ZOQwPqXRiXCPn9Pm5TOq8ajME2lM1YOJnN8D7bLh+Hmd1C9kxTN1RI1hDjQkVPvPy9ppE+tVxZyXXAn5IhW9jhW/sJU8r7EAoE2jLtY1v9uNYqyw7A6dfbq5aQ4PyIOWnW/WfmBQbLWm9BoCgLFqpI1CWBakOcnQHlziMgfIgMqZ1PwYP2Ov/vxDo7Dtr5dqu2Zrs+0T4yOZzEtMOlM3AqILmFk8phUfJ3ijhkvjF/t7zVrsQDnDo3Wnv5cGgXo8SUOp5FYWdcVQrUDTVS2tCcceuCIbDlIKy8Ib4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
