travis:
  secure:
    BINSTAR_TOKEN: FvDrUMm9BhNhSjfz+5HuHPFcymgvzS6j4F9s9PLKwk7HZjz5di4QYwTn6y8HFS+h4g3Oxbs9tiH70rWIaG5cyQbSf7cvn1dMazOBwv+hth/DwQaBDB4267ngy3c63sbUtdw4/G+yJ7C68qZfdlgoB+4iyc9dmOoA5qtiYMA1L+tAveN8EnquuMlbFB3sU3/XSvmaWvwhVVY1Fz+Ae0qadssNWwUwIbx8F3EPycbQB/jwueXWfgm7WyYrExT6dWNpnk9a3LuIA5nBi2YiG1km42aHEGmGaOlp/6oJ/RH/NXsc6uGOapmNRv5eiPEEJYvqEJSHmv/7oRe2rSDsvji6qLbng9TZ7fFcf1mma+EJTcIhcmlOJPMeqj6TfUD1TTNEsXK+NmeKBwJgDKwVFvFOzm+EO78NCpcSbJeHdVRRyD84MHznQiaidvsPX1W2hi64S8SXhBgIQn9Cs+Jc70qx4MFtkgPuEws63iBgarE5G6utThJv1ETWI4RfLwN0zQz028bkStNeubdmDyuWBMun6+8vIv4mtntQ4l7UmLEYbMM8XdB4fF1RaW2i7l/rOXvR9Arb9u/FiVqTLjTcJgWhII0ATXx0vy1mPwoNM3NFpsdWh7Bnp5FbLcmZp61UY55DUM1k8vtw6LW3iHEL5PZBBcEjDg4f/IaZcfPh6nEJnBg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
