appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: WlGcYVKA0JEgmZ1GvyQrqpXBE9bwbXjyikdGdSrbXx99ZrmxMEAbGL4prtzytAxJcwcXA7gxHYawF3sEDY3GMenhtqU/wdONTYfABHI2b+msT4PGQ6NFP5Muqo7FiDBOWOhjHtHK/AXdAt+91WnzuLQGTdXjaxXkRo85B4sSpSBn5YooV+PNC++qeUDtmYjPOVR4WDDvo07nzZF4/e4H/SQPFKp+axuPkTQ80ow0tya+buvzyIK6F6H0pqZXH9yD3GlNmrdQx2Sc8p3m5gF/FB5cHLP1HK/iMOgg9qJZtCi6GZTFzM9lmayGedFHYh7rSqMvaK7E8dcoEFOtCpSUJKNsM6R5Q76+SaczaFKFHs1N62JisFZU4gIuDLIablocRloeKj7mOe0YmNXwoMYLQnmz2uNzW+L5XNYjgcKjA/Vp4deUrrEAeYSTwz49Hdu4hBVAvcTEcrPGi+Jo50GrjPAVg8nMzmXciLKUApAzj4ZVXoXJcf+hQ0gt/25BxvKiQ1+pl7CO+TQsyLrI2CLuPA46eWARUYkJZZgFnejSA6/2dnrRjvRXTUVvi5bUlaVgAN82y7a+4y48xJ2X14O+dQPMLRBhhZ07hf9T/p6Pv4mrCqleiOGTOHke4wpc1yNkq3Ahqw+99jPxSW3P3mMCfBRfX5bgpNNkaOutFcrIjMA=
